# Generated by Django 3.1.6 on 2021-02-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lineDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataTime', models.CharField(max_length=200)),
                ('pm10Value', models.CharField(max_length=200)),
                ('pm25Value', models.CharField(max_length=200)),
                ('pm10Grade1h', models.CharField(max_length=200)),
                ('pm25Grade1h', models.CharField(max_length=200)),
            ],
        ),
    ]
