# Generated by Django 3.1.6 on 2021-02-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lineDb',
            new_name='AirChartDb',
        ),
    ]
