# Generated by Django 3.1.6 on 2021-02-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20210222_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airchartdb',
            name='dataTime',
            field=models.DateTimeField(),
        ),
    ]
