# Generated by Django 3.1.6 on 2021-02-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_auto_20210222_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airchartdb',
            name='pm10Grade1h',
        ),
        migrations.RemoveField(
            model_name='airchartdb',
            name='pm25Grade1h',
        ),
    ]
